name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Fix these violations
      run: ./gradlew :spotlessApply
    - name: Build with Gradle
      run: ./gradlew build
    - name: capture build artifacts
      if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: build/libs/
